### ISSUE TITLE
Unable to handle tags with namespace

### ISSUE THREAD

**Issue by mujahidmasood** [Chavaillaz/jaxb-stream#2]
`<?xml version='1.0' encoding='utf-8'?>
<ns:Test xmlns:ns="http://www.w3.org/2001/XMLSchema-instance">
    <ns:TestSub>
    </ns:TestSub>
</ns:TestSub>`

Fails to identify the namespaces correctly resulting in error below.

`javax.xml.stream.XMLStreamException: Unknown next type in the stream, check given ones in constructor or if skipDepth parameter in open method is correct
	at com.chavaillaz.jaxb.stream.StreamingUnmarshaller.lambda$getNextType$0(StreamingUnmarshaller.java:185)`

**Comment by Chavjoh** [comment]
Hello dear coder,

I think the problem comes from a misconfiguration on your side. You have to give the constructor of `StreamingUnmarshaller` **the list of expected types** in your files in order to retrieve them. Take a look at the examples in the test folder of the repository. If the problem persists, could you share a little bit more code ?
